using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BloggerAgent.Application.Dtos
{
    public class TaskResponse
    {
        public string Jsonrpc { get; set; }
        public string Id { get; set; }
        public Result Result { get; set; }
        public object? Error { get; set; }  // null here, but could be an error object if present

        public static object SendTaskResponse()
        {
            return new TaskResponse
            {
                Jsonrpc = "2.0",
                Id = "c006266b7e954f2fb07eb02b26ce6d9e",
                Result = new Result
                {
                    Id = "0195c514-2292-71e2-9378-21d11be2ad8c",
                    SessionId = "0195c514-2292-71e2-9378-21d11be2ad8c",
                    Status = new Status
                    {
                        State = "completed",
                        Message = new Message
                        {
                            Role = "agent",
                            Parts = new List<MessagePart>
                            {
                                new MessagePart
                                {
                                    Type = "text",
                                    Text = "Task completed with an artifact.",
                                    Metadata = null
                                }
                            },
                            Metadata = null
                        },
                        Timestamp = DateTime.Parse("2025-05-14T10:49:57.250107")
                    },
                    Artifacts = new List<Artifact>
                    {
                        new Artifact
                        {
                            Name = "sample_artifact",
                            Description = "A sample artifact generated by the system",
                            Parts = new List<ArtifactPart>
                            {
                                new ArtifactPart
                                {
                                    Type = "text",
                                    Text = "This is sample content in the artifact",
                                    Metadata = null
                                },
                                new ArtifactPart
                                {
                                    Type = "data",
                                    Data = new Dictionary<string, object>
                                    {
                                        { "key", "value" },
                                        { "example", 123 }
                                    },
                                    Metadata = null
                                }
                            },
                            Metadata = new Dictionary<string, object>
                            {
                                { "created_at", "2025-05-15T11:56:41.856473" }
                            },
                            Index = 0,
                            Append = null,
                            LastChunk = null
                        }
                    },
                    History = null,
                    Metadata = new Dictionary<string, object>
                    {
                        { "processed_at", "2025-05-15T11:56:41.856488" }
                    },
                    //Kind = "task"
                },
                Error = null
            };

        }
    }

    public class Result
    {
        public string Id { get; set; }
        public string SessionId { get; set; }
        public Status Status { get; set; }
        public List<Artifact> Artifacts { get; set; }
        public List<Message>? History { get; set; }
        public Dictionary<string, object>? Metadata { get; set; }
    }

    public class Status
    {
        public string State { get; set; }          // e.g., "completed"
        public Message Message { get; set; }
        public DateTime Timestamp { get; set; }
    }

    public class Artifact
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public List<ArtifactPart> Parts { get; set; }
        public Dictionary<string, object>? Metadata { get; set; }
        public int Index { get; set; }
        public object? Append { get; set; }
        public object? LastChunk { get; set; }
    }

    public class ArtifactPart
    {
        public string Type { get; set; }   // "text" or "data"
        public string? Text { get; set; }  // nullable because type might be "data"
        public Dictionary<string, object>? Data { get; set; }  // for "data" type
        public Dictionary<string, object>? Metadata { get; set; }
    }

}
